services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: db_app
    env_file:
      - .env
    environment:
      TZ: "Europe/Sofia"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
    volumes:
      - "./server:/var/run/mysqld"
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: data_app
    restart: always
    volumes:
      - "./:/data_app/"
      - "./server:/var/run/mysqld"
    ports:
      - "8000:8000"
    depends_on:
      - mysql