# Generated by Django 4.2.23 on 2025-07-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name_plural': 'Company Details'},
        ),
    ]
